In [10]:
from main import UserPredictor
import pandas as pd

model = UserPredictor()
train_users = pd.read_csv("train_users.csv")
train_logs = pd.read_csv("train_logs.csv")
train_y = pd.read_csv("train_y.csv")
model.fit(train_users,train_logs,train_y)
test_users = pd.read_csv("test1_users.csv")
test_logs = pd.read_csv("test1_logs.csv")
test_y = pd.read_csv("test1_y.csv")
y_pred = model.predict(test_users,test_logs)
# y_pred

In [11]:
model.score_Nixie(test_users, test_y, test_logs)

AVG: 0.7604333333333334, STD: 0.0049884310604081435

0.7613333333333333

In [12]:
model.hottie_userkt(train_users, train_logs)

,user_id,names,age,past_purchase_amt,badge,bronze,gold,silver,seconds_x,seconds_y
0,0,Adriana Mcclure,26,39.344704,gold,0.0,1.0,0.0,0.0,142.0
1,1,Stacy Gilmore,67,15.840151,silver,0.0,0.0,1.0,0.0,0.0
2,2,Joanna Walsh,50,1099.420085,bronze,1.0,0.0,0.0,0.0,0.0
3,3,Eduardo Moore,65,5.880239,bronze,1.0,0.0,0.0,0.0,0.0
4,4,Angela Freeman,88,1312.296847,bronze,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
29995,29995,William Lewis,87,108.914205,bronze,1.0,0.0,0.0,0.0,392.0
29996,29996,James Miranda,49,291.969273,gold,0.0,1.0,0.0,247.0,0.0
29997,29997,Carlos Davis,46,2.609698,bronze,1.0,0.0,0.0,0.0,0.0
29998,29998,Makayla Smith,23,164.885894,bronze,1.0,0.0,0.0,0.0,0.0
29999,29999,Tina Anderson,51,161.905284,gold,0.0,1.0,0.0,24.0,120.0